### ISSUE TITLE
Bloom Splitting Bug

### ISSUE THREAD

**Issue by BeeEnjoyer** [unforbidable/tfcplus-bids#9] opened 2024-06-27 16:16 UTC
Hello, I hope I'm doing it right. It seems that your mod in its current 44.1 version seems to break the bloom splitting process somehow, causing an immediate crash that persisted until had to remove the mod. It seems that it somehow spawns much more bloom pieces that it's meant to, as I have received 42 blooms out of 600-unit initial bloom. Crash report from most recent recreation included. Hope it helps.
[crash-2024-06-27_19.13.55-server.txt](https://github.com/user-attachments/files/16018050/crash-2024-06-27_19.13.55-server.txt)

**Comment by unforbidable** [comment] 2024-07-04 22:39
Hello, thanks for the report. I was able to find the cause of the crash quickly. The crash also seems to have caused the multiplication. Should be fixed in v0.44.2.

**Closed by unforbidable** 2024-07-04 22:39 UTC
Labels: bug
